import { getApps, initializeApp } from 'firebase/app';
import { createUserWithEmailAndPassword, getAuth, inMemoryPersistence, setPersistence, signInWithEmailAndPassword, signOut, type User } from 'firebase/auth';
import { firebaseConfig, getFirebase } from './firebase';
export const OWNER='vasquezpalparoy@gmail.com';
export const stages=[
 {title:'Requerimientos y diseño',subtitle:'Cotización',tasks:[['model','Modelo, tela, cuello y corte definidos'],['design','Diseño, logos, colores, nombres y números definidos'],['sizes','Tallas y cantidades confirmadas'],['quote','Precio, adelanto, fecha y método de pago acordados']]},
 {title:'Aprobación de muestra o arte',subtitle:'Preproducción',tasks:[['mockup','Maqueta digital aprobada por el cliente'],['sample','Muestra física aprobada (opcional)']]},
 {title:'Adelanto y confirmación',subtitle:'Ingreso a producción',tasks:[['registered','Pedido registrado'],['deposit','Adelanto recibido'],['queue','Pedido confirmado en la cola de producción']]},
 {title:'Producción',subtitle:'Fabricación',tasks:[['print','Impresión, sublimación o serigrafía'],['cut','Corte de las piezas según tallas'],['sew','Confección y costura'],['quality','Control de costuras, manchas e impresión']]},
 {title:'Acabados y empaque',subtitle:'Presentación final',tasks:[['threads','Limpieza de hilos sobrantes'],['iron','Planchado final'],['pack','Doblado y embolsado']]},
 {title:'Entrega y liquidación final',subtitle:'Cierre del pedido',tasks:[['notice','Cliente avisado: listo para recoger o despachar'],['balance','Saldo restante recibido'],['delivery','Entrega o envío realizado'],['receipt','Comprobante entregado y orden completada']]},
];
export type Order={id:string;reference:string;title:string;quantity:number;dueDate:string;notes:string;sampleRequired:boolean;checks:Record<string,boolean>;updatedAt:number};
export type Client={name:string;username:string;createdAt:number};
export type ClientRecord={profile:Client;orders?:Record<string,Order>};
export function isOwner(user:User|null){return !!user&&user.email?.toLowerCase()===OWNER&&user.emailVerified}
export function usernameEmail(value:string){const name=value.trim().toLowerCase();if(!/^[a-z0-9][a-z0-9._-]{2,39}$/.test(name))throw new Error('Usa entre 3 y 40 letras sin tildes, números, puntos, guiones o guiones bajos.');return name+'@clientes.hanna.invalid'}
export function getClientAuth(){const app=getApps().find(a=>a.name==='hanna-clientes')??initializeApp(firebaseConfig,'hanna-clientes');return getAuth(app)}
export async function clientLogin(username:string,password:string){return signInWithEmailAndPassword(getClientAuth(),usernameEmail(username),password)}
export async function clientLogout(){return signOut(getClientAuth())}
export function orderProgress(order:Order){const groups=stages.map(s=>s.tasks.filter(([key])=>key!=='sample'||order.sampleRequired));const total=groups.flat().length;const done=groups.flat().filter(([key])=>order.checks?.[key]).length;const complete=groups.map(g=>g.every(([key])=>order.checks?.[key]));const current=complete.findIndex(v=>!v);return {percent:Math.round(done/total*100),done,total,complete,current:current===-1?6:current}}
export function orderError(error:unknown){const code=(error as {code?:string})?.code;if(code==='auth/operation-not-allowed')return 'El acceso con usuario y contraseña todavía no está habilitado en Firebase.';if(['auth/invalid-credential','auth/user-not-found','auth/wrong-password','auth/invalid-email'].includes(code||''))return 'Usuario o contraseña incorrectos.';if(code==='auth/too-many-requests')return 'Demasiados intentos. Espera unos minutos y vuelve a intentar.';if(code==='auth/weak-password')return 'La contraseña debe cumplir la política de Firebase; usa al menos 8 caracteres.';if(code==='auth/network-request-failed')return 'No se pudo conectar. Revisa tu conexión.';return error instanceof Error?error.message:'No se pudo completar la operación.'}
async function request(path:string,user:User,method:'GET'|'PUT'='GET',value?:unknown,etag?:string){const token=await user.getIdToken();const url=new URL(firebaseConfig.databaseURL+'/hannaOrders'+path+'.json');url.searchParams.set('auth',token);const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),20000);try{const response=await fetch(url,{method,cache:'no-store',signal:controller.signal,headers:{'Content-Type':'application/json','X-Firebase-ETag':'true',...(etag?{'if-match':etag}:{})},body:method==='PUT'?JSON.stringify(value):undefined});const body=await response.json();if(response.status===412)throw new Error('Este pedido cambió en otra sesión. Actualiza la lista y vuelve a editarlo.');if(!response.ok)throw new Error(response.status===401||response.status===403?'Firebase no permitió acceder a los pedidos. Comprueba tu sesión y las reglas de pedidos.':'Firebase no pudo confirmar la operación. Vuelve a intentarlo.');return {data:body,etag:response.headers.get('ETag')||undefined}}catch(e){if((e as {name?:string}).name==='AbortError')throw new Error('Firebase no respondió a tiempo. Actualiza para comprobar si se guardó antes de reintentar.');throw e}finally{clearTimeout(timer)}}
export async function readClients(user:User){if(!isOwner(user))throw new Error('Entra con la cuenta de administración.');return normalizeClients((await request('',user)).data)}
export async function readMyOrders(user:User){return normalizeClient((await request('/'+user.uid,user)).data)}
export async function createClient(user:User,name:string,username:string,password:string){if(!isOwner(user))throw new Error('Entra con la cuenta de administración.');if(!name.trim())throw new Error('Escribe el nombre del cliente.');if(password.length<8)throw new Error('Usa una contraseña de al menos 8 caracteres.');const email=usernameEmail(username);const app=getApps().find(a=>a.name==='hanna-provision')??initializeApp(firebaseConfig,'hanna-provision');const auth=getAuth(app);await setPersistence(auth,inMemoryPersistence);try{let credential;try{credential=await createUserWithEmailAndPassword(auth,email,password)}catch(e){if((e as {code?:string}).code!=='auth/email-already-in-use')throw e;credential=await signInWithEmailAndPassword(auth,email,password)}const uid=credential.user.uid;const existing=await request('/'+uid,user);if(existing.data?.profile)throw new Error('Este usuario ya está registrado. Selecciónalo en la lista para añadir un pedido.');const profile:Client={name:name.trim(),username:username.trim().toLowerCase(),createdAt:Date.now()};await request('/'+uid,user,'PUT',{profile},existing.etag);return uid}finally{await signOut(auth)}}
export async function loadOrder(user:User,uid:string,id:string){const r=await request('/'+uid+'/orders/'+id,user);return {order:r.data?{...r.data,checks:r.data.checks||{}} as Order:null,etag:r.etag}}
export async function saveOrder(user:User,uid:string,order:Order,etag?:string){if(!isOwner(user))throw new Error('Solo HANNA puede modificar el avance.');if(!order.title.trim()||!order.reference.trim())throw new Error('Completa el número y la descripción del pedido.');if(!Number.isInteger(order.quantity)||order.quantity<1)throw new Error('La cantidad debe ser un número entero mayor que cero.');const result=await request('/'+uid+'/orders/'+order.id,user,'PUT',{...order,title:order.title.trim(),reference:order.reference.trim(),updatedAt:{'.sv':'timestamp'}},etag);return {...result,data:{...result.data,checks:result.data.checks||{}}}}
export function emptyOrder():Order{return {id:crypto.randomUUID(),reference:'',title:'',quantity:1,dueDate:'',notes:'',sampleRequired:false,checks:{},updatedAt:0}}

function normalizeClient(value:ClientRecord|null):ClientRecord|null {if(!value)return null;return {...value,orders:Object.fromEntries(Object.entries(value.orders||{}).map(([id,o])=>[id,{...o,checks:o.checks||{}}]))}}
function normalizeClients(value:Record<string,ClientRecord>|null):Record<string,ClientRecord>|null{return value?Object.fromEntries(Object.entries(value).map(([uid,c])=>[uid,normalizeClient(c)!])):null}
